### ISSUE TITLE
Piwigo crashed on CRFG site

### ISSUE THREAD

**Issue by fyliu** [fyliu/crfg-site#13]
# Sympton

- Error message when requesting https://crfg.org/piwigo/

> Warning: [mysql error 145] Table './crfgor5_piwi386/piwisw_images' is marked as crashed and should be repaired
> 
> SELECT
>     category_id
>   FROM piwisw_image_category
>     JOIN piwisw_images ON image_id = id
>   WHERE category_id IN (47)
>     AND level > 0
>     AND level <= 8
>   GROUP BY category_id
> ; in /home/crfgor5/public_html/piwigo/include/dblayer/functions_mysqli.inc.php on line 856
> 
> 
> Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /home/crfgor5/public_html/piwigo/include/dblayer/functions_mysqli.inc.php:909 Stack trace: #0 /home/crfgor5/public_html/piwigo/include/functions.inc.php(1517): query2array('\nSELECT\n cat...', 'category_id') #1 /home/crfgor5/public_html/piwigo/plugins/community/include/functions_community.inc.php(197): hash_from_query('\nSELECT\n cat...', 'category_id') #2 /home/crfgor5/public_html/piwigo/plugins/community/main.inc.php(48): community_get_user_permissions('2') #3 /home/crfgor5/public_html/piwigo/include/functions_plugins.inc.php(264): community_init() #4 /home/crfgor5/public_html/piwigo/include/common.inc.php(293): trigger_notify('init') #5 /home/crfgor5/public_html/piwigo/index.php(11): include_once('/home/crfgor5/p...') #6 {main} thrown in /home/crfgor5/public_html/piwigo/include/dblayer/functions_mysqli.inc.php on line 909

**Comment by fyliu** [comment]
Resolved by repairing piwisw_images table from phpMyAdmin

Reference of several methods:
https://stackoverflow.com/questions/4357270/table-is-marked-as-crashed-and-should-be-repaired

**Comment by fyliu** [comment]
Possible explanations of why it happened:
https://www.stellarinfo.com/blog/fix-mysql-is-marked-as-crashed-and-should-be-repaired/
